author = 'Nate Vack'
email = 'njvack@wisc.edu'
version = '0.1.0dev'
license = 'MIT license'
copyright = 'Copyright (c) 2017 Board of Regents of the University of Wisconsin System'
url = 'https://github.com/njvack/masterfile'
